workflows:
  android-workflow:
    name: Build DoorDash Analyzer
    max_build_duration: 

    scripts:
  - name: Compilar APK
    script: ./gradle/wrapper/gradle-wrapper.jar assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - TU_EMAIL@ejemplo.com
